//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrimeCategory
    {
        public CrimeCategory()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public string crimetype { get; set; }
        public int Intensity { get; set; }
    
        public virtual ICollection<Report> Report { get; set; }
    }
}
