//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeofenceCoordinates
    {
        public int id { get; set; }
        public int geofenceid { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public int OrderIndex { get; set; }
    
        public virtual Geofences Geofences { get; set; }
    }
}
