//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geofences
    {
        public Geofences()
        {
            this.GeofenceCoordinates = new HashSet<GeofenceCoordinates>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int policestationid { get; set; }
    
        public virtual ICollection<GeofenceCoordinates> GeofenceCoordinates { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
    }
}
