//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> userId { get; set; }
        public string category { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string description { get; set; }
        public string gender { get; set; }
        public System.TimeSpan reportTime { get; set; }
        public System.DateTime reportDate { get; set; }
        public Nullable<bool> isVerified { get; set; }
        public string address { get; set; }
    
        public virtual PoliceStation PoliceStation { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
