//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> recipientId { get; set; }
        public decimal senderLatitude { get; set; }
        public decimal senderLongitude { get; set; }
        public System.DateTime notifyDate { get; set; }
        public System.TimeSpan notifyTime { get; set; }
        public Nullable<bool> isSeen { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
    }
}
