//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceStation
    {
        public PoliceStation()
        {
            this.Geofences = new HashSet<Geofences>();
            this.Report = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public string station_name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public bool isApproved { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Geofences> Geofences { get; set; }
        public virtual ICollection<Report> Report { get; set; }
    }
}
