//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> userId { get; set; }
        public string crimetype { get; set; }
        public System.DateTime reportdate { get; set; }
        public System.TimeSpan reporttime { get; set; }
        public string description { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string affectedgender { get; set; }
        public bool isVerified { get; set; }
    
        public virtual CrimeCategory CrimeCategory { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
