//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafeZoneEntities : DbContext
    {
        public SafeZoneEntities()
            : base("name=SafeZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<CrimeCategory> CrimeCategory { get; set; }
        public DbSet<GeofenceCoordinates> GeofenceCoordinates { get; set; }
        public DbSet<Geofences> Geofences { get; set; }
        public DbSet<PoliceStation> PoliceStation { get; set; }
        public DbSet<Relation> Relation { get; set; }
        public DbSet<Report> Report { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
    }
}
