//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.History = new HashSet<History>();
            this.Relation = new HashSet<Relation>();
            this.Relation1 = new HashSet<Relation>();
            this.Report = new HashSet<Report>();
            this.Notification = new HashSet<Notification>();
            this.Notification1 = new HashSet<Notification>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string cnic { get; set; }
        public string gender { get; set; }
    
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<Relation> Relation { get; set; }
        public virtual ICollection<Relation> Relation1 { get; set; }
        public virtual ICollection<Report> Report { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<Notification> Notification1 { get; set; }
    }
}
